print("Hello, ab(user)")
print("""乁༼☯‿☯✿༽ㄏ""")
word1 = str(input("First vegetable: "))
word2 = str(input("Second vegetable: "))
word3 = str(input("Third vegetable: "))
print(str.lower(word1),str.lower(word2),str.lower(word3))
print(str.upper(word1),str.upper(word2),str.upper(word3))
print ("Enter amount of ", str.capitalize(word1),":")
n1 = input()
chars = set('0123456789$,')
while any((let not in chars) for let in n1) :
     print("Are u a hoe?/?")
     n1 = input()
print ("Enter amount of ", str.capitalize(word2),":")
n2 = (input())
while any((let not in chars) for let in n2) :
     print("Are u a hoe?7?")
     n2 = input()
print ("Enter amount of ", str.capitalize(word3),":")
n3 = (input())
while any((let not in chars) for let in n3) :
     print("Are u a crab?7??")
     n3 = input()
print (str.capitalize(word1)+"s:",n1,";",str.capitalize(word2)+"s:",n2,";",str.capitalize(word3)+"s:",n3,";")